server:
  port: 8888
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: redis123
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: guest
    username: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rayson?useSSL=false
    username: root
    password: 199011081108
  liquibase:
    change-log: classpath:/scripts/db/changelog/db.changelog-master.xml
  data:
    elasticsearch:
      cluster-name: rayest
      cluster-nodes: elasticsearch

nettyServer:
  ioThreadNum:  5
  backlog: 1024
  port: 9624
  host: 0.0.0.0
